#!/usr/bin/env php

<?php

use Mustafa\PhpWebserver\Request;
use Mustafa\PhpWebserver\Response;
use Mustafa\PhpWebserver\Server;

require_once __DIR__ . '/vendor/autoload.php';

array_shift($argv);

empty($argv) ? $port = 80 : $port = array_shift($argv);

$server = new Server('127.0.0.1:', $port);

$server->listen(function (Request $request){
    echo $request->getMethod() . ' ' . $request->getUri() . "\n";

    return new Response('<pre>' . print_r($request, true ) . '</pre>');
});